# vendor/anfallnorr/file-manager-system/config/routes.yaml
file_manager_system:
    # resource: '@FileManagerSystemBundle/Controller/'
    # resource: '@FileManagerSystem/Controller/'
    resource: ../src/Controller/
    type: attribute
    prefix: /files-manager
